"""
Module to initialize parameter tuning.
"""

from models.parameter_tuning.parameter_tuning_processor import ParameterTuningProcessor
from models.parameter_tuning.ma_parameter_tuning import MovingAverageParameterTuning
from models.parameter_tuning.momentum_parameter_tuning import MomentumParameterTuning
from models.parameter_tuning.in_and_out_momentum_parameter_tuning import InAndOutMomentumParameterTuning
