"""
Module to initialize momentum_models.
"""

from models.backtest_models.backtesting_processor import BacktestingProcessor

from models.backtest_models.hierarchical_clustering import BacktestClusteringPortfolio
from models.backtest_models.iao_momentum_backtest import BacktestInAndOutMomentumPortfolio
from models.backtest_models.momentum_backtest import BacktestMomentumPortfolio
from models.backtest_models.sma_backtesting import SmaBacktestPortfolio
