from enum import Enum

class PortfolioWeightingFormula(Enum):
    MV = "Standard Deviation"
    KT = "Square Root Kurtosis"
    MAD = "Mean Absolute Deviation"
    MSV = "Semi Standard Deviation"
    SKT = "Square Root Semi Kurtosis"
    FLPM = "First Lower Partial Moment (Omega Ratio)"
    SLPM = "Second Lower Partial Moment (Sortino Ratio)"
    VaR = "Value at Risk"
    CVaR = "Conditional Value at Risk"
    EVaR = "Entropic Value at Risk"
    WR = "Worst Realization (Minimax)"
    CVRG = "CVaR range of returns"
    MDD = "Maximum Drawdown of uncompounded cumulative returns (Calmar Ratio)"
    ADD = "Average Drawdown of uncompounded cumulative returns"
    DaR = "Drawdown at Risk of uncompounded cumulative returns"
    CDaR = "Conditional Drawdown at Risk of uncompounded cumulative returns"
    EDaR = "Entropic Drawdown at Risk of uncompounded cumulative returns"
    MDD_Rel = "Maximum Drawdown of compounded cumulative returns (Calmar Ratio)"
    ADD_Rel = "Average Drawdown of compounded cumulative returns"
    DaR_Rel = "Drawdown at Risk of compounded cumulative returns"
    CDaR_Rel = "Conditional Drawdown at Risk of compounded cumulative returns"
    EDaR_Rel = "Entropic Drawdown at Risk of compounded cumulative returns"
